<?php

namespace AppBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEventsByTag(string $label)
    {
        $query = $this->createQueryBuilder('e')
            ->join('e.tags', 't')
            ->where('t.label LIKE :label')
            ->setParameter('label', '%' . $label . '%')
            ->getQuery();

        return $query->getResult();
    }

    public function findEventsWhoHaveEditionByDate(\DateTime $dateTime)
    {
        $query = $this->createQueryBuilder('e')
            ->join('e.editions', 'ed')
            ->where('ed.startDate > :nowDate')
            ->setParameter('nowDate', $dateTime)
            ->getQuery()
            ->getResult()
        ;
        return $query;
    }
}
