<?php

namespace AppBundle\Repository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByLike(string $label)
    {
        return $this->createQueryBuilder('t')
                ->where('t.label LIKE :label')
                ->setParameter('label', '%' . $label . '%')
                ->getQuery()
                ->getResult();
    }
}
